#!/bin/bash
# extract-chromosomes-3 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {



    mkdir -p /input/Sorted_Bam
    mkdir -p /out/Filtered_Bam

    echo "Value of Chromosome_List: '${Chromosome_List}'"

    #download the sorted bam
    echo "Downloading sorted BAM file '${Sorted_Bam_name}'"
    dx download "${Sorted_Bam}" -o /input/Sorted_Bam/${Sorted_Bam_name}

    echo "Downloading sorted BAM file '${Sorted_Bam_Index_name}'"
    dx download "${Sorted_Bam_Index}" -o /input/Sorted_Bam/${Sorted_Bam_Index_name}


    echo "Downloading the docker image..."
    dx-docker pull artifacts/variationanalysis-app:latest &>/dev/null

    cpus=`grep physical  /proc/cpuinfo |grep id|wc -l`

    dx-docker run \
        -v /input/:/input \
        -v /out/:/out \
        artifacts/variationanalysis-app:latest \
        bash -c "source ~/.bashrc; cd /out/Filtered_Bam; extract-chromosomes.sh ${cpus} /input/Sorted_Bam/${Sorted_Bam_name} \"${Chromosome_List}\""

    ls -lrt /out/Filtered_BAM
    mkdir -p $HOME/out
    mv /out/Filtered_BAM $HOME/out

    echo "Files to publish"
    ls -lrt $HOME/out
    dx-upload-all-outputs --parallel

}
