#!/bin/bash
# parallel-gatk-realigner 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    mkdir -p /input/scripts/
    mkdir -p /input/Sorted_Bam
    mkdir -p /input/FASTA_Genome
    mkdir -p /out/Realigned_Bam

    #download the sorted bam
    for i in ${!Sorted_Bam[@]}
    do
        echo "Downloading sorted BAM file '${Sorted_Bam_name[$i]}'"
        dx download "${Sorted_Bam[$i]}" -o /input/Sorted_Bam/${Sorted_Bam_name[$i]}
    done
    set -x
    #download the gzipped genome
    echo "Downloading genome file '${Genome_name}'"
    dx download "${Genome}" -o /input/FASTA_Genome/${Genome_name}
    #unzip
    (cd /input/FASTA_Genome; gunzip ${Genome_name})

    dx-docker pull artifacts/variationanalysis-app:latest

    #index the genome with samtools and create the dictionary
    genome_name=`basename /input/FASTA_Genome/*.fa* | cut -d. -f1`
    genome_basename=`basename /input/FASTA_Genome/*.fa*`

    cat >/input/scripts/index.sh <<EOL
    #!/bin/bash
    set -x
    ls -lrt  /input/FASTA_Genome/
    cd /input/FASTA_Genome
    samtools faidx /input/FASTA_Genome/*.fa*
    ls -lrt  /input/FASTA_Genome/
    java -jar /root/picard/picard.jar CreateSequenceDictionary R= /input/FASTA_Genome/${genome_basename} O= /input/FASTA_Genome/${genome_name}.dict
EOL
    chmod u+x /input/scripts/index.sh

    #index
    dx-docker run \
        -v /input/:/input \
        artifacts/variationanalysis-app:latest \
        bash -c "source ~/.bashrc; cd /input/FASTA_Genome; /input/scripts/index.sh"

    bam_basename=`basename /input/Sorted_Bam/*.bam | cut -d. -f1`
    cpus=`grep physical  /proc/cpuinfo |grep id|wc -l`

    # get GATK 4 from dropbox (until it is officially released)
    wget -O /input/gatk-4.beta.5.zip https://www.dropbox.com/s/e7vruiwqd9k52md/gatk-4.beta.5.zip
    cd /input
    unzip gatk-4.beta.5.zip
    cd
    dx-docker run \
        -v /input/:/input \
        -v /out/:/out \
        artifacts/variationanalysis-app:latest \
        bash -c "source ~/.bashrc; cd /out/Realigned_Bam && parallel-gatk-realign-filtered.sh /input/gatk-4.beta.5/gatk-launch 6g ${cpus} /input/FASTA_Genome/${genome_basename} /input/Sorted_Bam/${bam_basename}.bam /out/Realigned_Bam/${bam_basename}-realigned.bam \"${GATK_Arguments}\""


    mkdir -p $HOME/out/Realigned_Bam
    mv /out/Realigned_Bam/*-realigned.bam $HOME/out/Realigned_Bam/
    mv /out/Realigned_Bam/*-realigned.bam.bai $HOME/out/Realigned_Bam/
    ls -lrt $HOME/out/Realigned_Bam/
    dx-upload-all-outputs

}
