#!/bin/bash
# parallel-gatk-realigner 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    mkdir -p /input/scripts/
    mkdir -p /input/Sorted_Bam
    mkdir -p /input/FASTA_Genome
    mkdir -p /out/Realigned_Bam

    #download the sorted bam
    for i in ${!Sorted_Bam[@]}
    do
        echo "Downloading sorted BAM file '${Sorted_Bam_name[$i]}'"
        dx download "${Sorted_Bam[$i]}" -o /input/Sorted_Bam/${Sorted_Bam_name[$i]}
    done
    set -x
    #download the gzipped genome
    echo "Downloading genome file '${Genome_name}'"
    dx download "${Genome}" -o /input/FASTA_Genome/${Genome_name}
    #unzip
    (cd /input/FASTA_Genome; gunzip ${Genome_name})

    genome_basename=`basename /input/FASTA_Genome/*.fasta`
    bam_basename=`basename /input/Sorted_Bam/*.bam | cut -d. -f1`

    cat >/input/scripts/configure.sh <<EOL
    #!/bin/bash
    cd /out/Realigned_Bam
    export GATK_LAUNCH=/input/gatk-package-4.beta.1-local.jar
    export MEMORY_PER_THREAD=6g
    export NUM_THREADS=`grep physical  /proc/cpuinfo |grep id|wc -l`
    export FASTA_GENOME=/input/FASTA_Genome/${genome_basename}
    export BAM_INPUT=/input/Sorted_Bam/${bam_basename}.bam
    export BAM_OUTPUT=/out/Realigned_Bam/${bam_basename}-realigned.bam
    export GATK_ARGS="${GATK_Arguments}"
EOL
    chmod u+x /input/scripts/configure.sh

    # get GATK 4 from dropbox (until it is officially released)
    wget -O /input/gatk-package-4.beta.1-local.jar https://www.dropbox.com/s/oko590zxebhlqmg/gatk-package-4.beta.1-local.jar
    dx-docker pull artifacts/variationanalysis-app:latest

    dx-docker run \
        -v /input/:/input \
        -v /out/:/out \
        artifacts/variationanalysis-app:latest \
        bash -c "source ~/.bashrc; source /input/scripts/configure.sh; parallel-gatk-realign-filtered.sh ${GATK_LAUNCH} ${MEMORY_PER_THREAD} ${NUM_THREADS} ${FASTA_GENOME} ${BAM_INPUT} ${BAM_OUTPUT} \"${GATK_ARGS}\""


    mkdir -p $HOME/out/Realigned_Bam
    mv /out/Realigned_Bam/*-realigned.bam $HOME/out/Realigned_Bam/
    mv /out/Realigned_Bam/*-realigned.bam.bai $HOME/out/Realigned_Bam/
    ls -lrt $HOME/out/Realigned_Bam/
    dx-upload-all-outputs

}
